<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <AssemblyName>xPilot.PluginSdk</AssemblyName>
    <RootNamespace>Vatsim.Xpilot.PluginSdk</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <DebugType>embedded</DebugType>
  </PropertyGroup>
</Project>
